[build]
  command = """
    echo "⚡ Generating env.json from Netlify ENV VARS..."
    mkdir -p build/web/assets
    echo "GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID" > build/web/assets/env.json
    echo "GOOGLE_API_KEY=$GOOGLE_API_KEY" >> build/web/assets/env.json
    echo "ADMIN_EMAILS=$ADMIN_EMAILS" >> build/web/assets/env.json
    echo "DRIVE_FOLDER_ID=$DRIVE_FOLDER_ID" >> build/web/assets/env.json
    flutter build web --release
    echo "✅ env.json copied to build/web/assets/env.json"
  """
  publish = "build/web"

[build.environment]
  FLUTTER_VERSION = "3.22.2"

[[plugins]]
  package = "netlify-plugin-flutter"
