[build]
  command = """
    echo "⚡ Generating assets/.env from Netlify ENV VARS..."
    mkdir -p assets
    echo "GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID" > assets/.env
    echo "GOOGLE_API_KEY=$GOOGLE_API_KEY" >> assets/.env
    echo "ADMIN_EMAILS=$ADMIN_EMAILS" >> assets/.env
    echo "DRIVE_FOLDER_ID=$DRIVE_FOLDER_ID" >> assets/.env
    echo "✅ .env generated successfully!"
    cat assets/.env
    flutter build web --release
  """
  publish = "build/web"

[build.environment]
  FLUTTER_VERSION = "3.22.2"

[[plugins]]
  package = "netlify-plugin-flutter"
