[build]
  command = """
    echo "⚡ Generating .env from Netlify ENV VARS..."
    echo "GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID" > .env
    echo "GOOGLE_API_KEY=$GOOGLE_API_KEY" >> .env
    echo "ADMIN_EMAILS=$ADMIN_EMAILS" >> .env
    echo "DRIVE_FOLDER_ID=$DRIVE_FOLDER_ID" >> .env
    flutter build web --release
    mkdir -p build/web/assets
    cp .env build/web/assets/.env
    echo "✅ .env copied to build/web/assets/.env"
  """
  publish = "build/web"

[build.environment]
  FLUTTER_VERSION = "3.22.2"

[[plugins]]
  package = "netlify-plugin-flutter"
